#!/bin/bash
#Description: Wrapper for github-flavored-markdown.rb
#Source: https://github.com/nodiscc/scriptz
#License: MIT

#TODO: include css in file


cat > $OutputFile << ENDHEADER
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Default template</title>
    <meta name="description" content="">

    <!-- Le styles -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="css/bootstrap-docs.css" rel="stylesheet">
    <link href="google-code-prettify/prettify.css" rel="stylesheet">
    <link href="css/template.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">

	    <section>
ENDHEADER



Dir=$(dirname "$0")
    # Compiles the markdown (and sed will rename the .md links)
    bin/github-flavored-markdown.rb ${SOURCE_FILE} | sed 's|<a href="\([^"]*\)\.md"|<a href="\1"|g' >> ${OUTPUT_FILE}


##Start printing HTML footer
cat > $OutputFile << ENDFOOTER
		</section>
	
    </div><!-- /container -->

        <footer class="footer">
            <div class="container">
                <p class="pull-right"><a href="#">Back to top</a></p>
                <p>
                    Documentation generated by
                    <a href="http://mnapoli.github.com/gh-pages-compiler/" target="_blank">gh-pages-compiler</a>.
                </p>
            </div>
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="google-code-prettify/prettify.js"></script>

        <script>
            $(function() {
                $("section h1").wrap(\'<div class="page-header" />\');
                $("section p:first-child").addClass(\'lead\');
                $("pre").addClass(\'prettyprint\');
                prettyPrint();
            });
        </script>

  </body>
</html>
ENDFOOTER